<?php

    /**
     * Content for the 'dashboard page'
     */
    function action_logger_dashboard() {

        if ( ! current_user_can( 'edit_users' ) ) {
            wp_die( __( 'Sorry, you do not have sufficient permissions to access this page.', 'action-logger' ) );
        }

        echo '<div class="wrap">';
        
        echo "<h1>Action Logger overview</h1>";

        ActionLogger::al_show_admin_notices();
        // hook before list
        do_action('al_before_overview', '' );

        echo '<div id="action-logger" class="">';

        // get results from db
        global $wpdb;
        $items = array();
        $items = $wpdb->get_results( "
                SELECT * FROM " . $wpdb->prefix . "action_logs
                order by id DESC
            ");

        echo ActionLogger::al_admin_menu();

        if ( count( $items ) == 0 ) {
            ?>
            <p><?php esc_html_e( 'No logs (yet)...', 'action-logger' ); ?></p>
            <?php
        } elseif ( count( $items ) > 0 ) {
            rsort( $items );
            ?>
            <p><?php esc_html_e( 'This page shows a log of all actions done by users, which are "interesting" to log.', 'action-logger' ); ?></p>
            <h2><?php esc_html_e( 'Logs', 'action-logger' ); ?></h2>
            <p><small><?php esc_html_e( 'Log items are sorted, newest to oldest.', 'action-logger' ); ?></small></p>
            <form name="logs-form" action="" method="post">
                <input name="delete_action_items_nonce" type="hidden" value="<?php echo wp_create_nonce( 'delete-actions-items-nonce' ); ?>" />
                <table>
                    <thead>
                    <tr class="row">
                        <th class="datetime"><?php esc_html_e( 'Date/time', 'action-logger' ); ?></th>
                        <?php if ( current_user_can( 'manage_options' ) ) { ?>
                            <th class="action"><?php esc_html_e( 'Action', 'action-logger' ); ?></th>
                        <?php } ?>
                        <th class="generator"><?php esc_html_e( 'Generated by', 'action-logger' ); ?></th>
                        <th class="description"><?php esc_html_e( 'Description', 'action-logger' ); ?></th>
                        <?php if ( current_user_can( 'manage_options' ) ) { ?>
                            <th class=""><?php esc_html_e( 'Delete', 'action-logger' ); ?></th>
                        <?php } ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach( $items as $item ) {
                            ?>
                            <tr class="row">
                                <td class="datetime"><?php echo date( 'M j @ H:i:s', $item->action_time ); ?> (+<?php echo get_option( 'gmt_offset' ); ?>)</td>
                                <?php if ( current_user_can( 'manage_options' ) ) { ?>
                                    <td class="action"><?php echo $item->action; ?></td>
                                <?php } ?>
                                <td class="generator"><?php echo $item->action_generator; ?></td>
                                <td class="description"><?php echo $item->action_description; ?></td>
                                <?php if ( current_user_can( 'manage_options' ) ) { ?>
                                    <td class="checkbox">
                                        <label for="rows" class="screen-reader-text">
                                            <?php esc_html_e( 'Delete', 'action-logger' ); ?>
                                        </label>
                                        <input name="rows[]" id="rows" type="checkbox" value="<?php echo $item->id; ?>" />
                                    </td>
                                <?php } ?>
                            </tr>
                            <?php
                        }
                    ?>
                    </tbody>
                </table>
                <?php if ( current_user_can( 'manage_options' ) ) { ?>
                    <br />
                    <input name="delete" type="submit" class="admin-button admin-button-small" value="<?php esc_html_e( 'Delete selected items', 'action-logger' ); ?>" />
                <?php } ?>
            </form>
            <?php
        }

        echo '</div>'; // end #action-logger

        // hook after list
        do_action('al_after_overview' );

        echo '</div><!-- end .wrap -->';
    }
